<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button tambah</name>
   <tag></tag>
   <elementGuidId>897a6db7-fae1-46c0-ac9f-2182e85287bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>039f50cf-31a0-44d7-993e-0d3c83a7006d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grey_btn mr10</value>
      <webElementGuid>53fa5e9b-7893-43b9-984e-94b830af4081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tambah</value>
      <webElementGuid>3b9fdd0a-56e7-4c11-abad-8671f17b138b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>a8f3efd0-65ac-4e39-8c81-83779b2ff236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>bf2dae4f-0d54-4af1-acfe-a145df77cb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>07e3d91d-a8ad-45d3-aa86-bdb58d3eb5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add&quot;)</value>
      <webElementGuid>964ecc7a-9e74-48c3-abb7-6ade8bf6310c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add']</value>
      <webElementGuid>ed5ba9ae-cb55-4b88-983d-3d3cd0e8c9f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/input</value>
      <webElementGuid>bcc22b99-e31f-419f-aa18-cbb7a4f5952d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>eaab3d64-cc4d-43b9-ac16-4a3f02da4407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'add' and @name = 'add' and @type = 'submit']</value>
      <webElementGuid>e45754cc-0fbb-4766-9c69-74b7c61082e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
