<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input MDR</name>
   <tag></tag>
   <elementGuidId>1b10e2e7-a280-4a11-bce9-6f8fcc6105f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='merchantMdr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#merchantMdr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f4ffad4-8b52-4a74-aa68-d507154ea83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>customMdr()</value>
      <webElementGuid>b6adce05-739e-4bf6-85e1-3f199eafcdd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>inputDigitsAndDotPercent(event)</value>
      <webElementGuid>f9d99dfe-302d-45d5-bab2-03536d2054e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>merchantMdr</value>
      <webElementGuid>1176291f-2b40-453e-99bd-56f69cfee632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>merchantMdr</value>
      <webElementGuid>b5d54ece-b56a-4501-b842-8df66b0de6c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c61857ed-ec27-493e-b23a-abaa2fe65e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;merchantMdr&quot;)</value>
      <webElementGuid>5b37d263-4266-4f14-ba29-73fa6e695b9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='merchantMdr']</value>
      <webElementGuid>503d6be5-4ef8-439b-903f-dcc802001958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mdrZone']/input</value>
      <webElementGuid>fb9d820a-6d07-470d-bff9-c12689ca02b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/input</value>
      <webElementGuid>538beed9-2882-4795-b795-12ac7e15c1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'merchantMdr' and @name = 'merchantMdr' and @type = 'text']</value>
      <webElementGuid>e0b97159-519a-4f87-af4b-0f83c5f03595</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
