<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pilih Kiteria</name>
   <tag></tag>
   <elementGuidId>8e308b11-2a02-4aeb-b387-1dbf44f32f41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='merchantCriteriaId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#merchantCriteriaId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4e81d9c7-abd8-4fb1-872c-ae0748f5aca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>merchantCriteriaId</value>
      <webElementGuid>c4814fa5-78e9-4937-bb85-aadc2362c643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>merchantCriteriaId</value>
      <webElementGuid>5b2a6144-e672-4be8-ad15-ad6eeaf41759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[Pilih Kriteria]</value>
      <webElementGuid>60e838ff-b4f6-40bd-9259-26556f9f08f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;merchantCriteriaId&quot;)</value>
      <webElementGuid>74f684d0-a537-45ab-85e6-2b912a32026d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='merchantCriteriaId']</value>
      <webElementGuid>7757c014-d55f-4c00-b018-2c01b8408fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='categoryZone']/select</value>
      <webElementGuid>f2d477dd-4010-4d45-affd-ef406f606a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kriteria'])[1]/following::select[1]</value>
      <webElementGuid>f2824ad2-846a-4b8c-9850-2ab20e1f0560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::select[2]</value>
      <webElementGuid>06e5c843-fd4d-4169-b886-bfaa964ddf00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MDR'])[1]/preceding::select[1]</value>
      <webElementGuid>b8cd20ea-4c29-4358-a297-345675d3d5d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan'])[1]/preceding::select[1]</value>
      <webElementGuid>144964fe-fc7b-47ec-93ba-9119b7bbcb0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/select</value>
      <webElementGuid>41ae2b24-0a48-49e2-9056-2e08be1d4227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'merchantCriteriaId' and @name = 'merchantCriteriaId' and (text() = '[Pilih Kriteria]' or . = '[Pilih Kriteria]')]</value>
      <webElementGuid>8d639557-9ffb-4e9a-b5be-84de2ad90e83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
