<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pilih Katagori</name>
   <tag></tag>
   <elementGuidId>3ab1722a-806c-4c2b-ae48-f068af6c36d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='globalCategory']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#globalCategory</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>22e0f15a-df43-40cf-96d5-2d61d242e715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>globalCategory</value>
      <webElementGuid>a1d4c92f-a3b6-4141-bf60-9bbeaec63571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>globalCategory</value>
      <webElementGuid>7ab15839-5b73-4072-93de-8c419f50815c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[Pilih Kategori]RegularKhusus</value>
      <webElementGuid>f6657bfb-7d59-42ed-8431-6b5595b34a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;globalCategory&quot;)</value>
      <webElementGuid>fecf4d83-0b90-43df-a7b8-267e959fbe15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='globalCategory']</value>
      <webElementGuid>8502c5a0-4c7f-456c-b179-eea88bae8ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr/td[2]/select</value>
      <webElementGuid>5b743ddf-a3d1-42a7-9978-99471771599c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::select[1]</value>
      <webElementGuid>7f35cfbc-5da4-4410-89c9-82f88b83391b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance Kategori Merchant QRIS'])[1]/following::select[1]</value>
      <webElementGuid>05945344-0d9a-4462-b725-0d791de0beac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kriteria'])[1]/preceding::select[1]</value>
      <webElementGuid>ce6f4f30-2e5d-4dcb-a4fe-9d90187859eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MDR'])[1]/preceding::select[2]</value>
      <webElementGuid>c443698c-525f-4687-9c19-1947d0485c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6629b83d-e560-4a53-ae67-25d49151d9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'globalCategory' and @name = 'globalCategory' and (text() = '[Pilih Kategori]RegularKhusus' or . = '[Pilih Kategori]RegularKhusus')]</value>
      <webElementGuid>49505440-6d87-4375-83e3-a43791f64191</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
