<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Ubah</name>
   <tag></tag>
   <elementGuidId>532a0378-6e79-477f-9008-e53227daf264</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form']/div[2]/table/tbody/tr[1]/td[3]/a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.action > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3d1c7ce4-8891-4f95-ac02-f3940ba2e4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/emoney-admin/ind/user/approval/roleapprovallist:viewdetail/142?_csrf=bca5cf9a-b101-46b0-8113-a26978c29910</value>
      <webElementGuid>09906bf4-6766-4276-8293-54ba94d1767d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah</value>
      <webElementGuid>eec8cda5-10c6-41b2-bea4-2073b212175a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;t-data-grid&quot;]/table[@class=&quot;t-data-grid&quot;]/tbody[1]/tr[@class=&quot;t-first&quot;]/td[@class=&quot;action&quot;]/a[1]</value>
      <webElementGuid>5a477f62-ba97-409f-aebd-b90afcd9b80e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[2]/table/tbody/tr/td[3]/a</value>
      <webElementGuid>1ae105a8-6360-4ddf-b92d-cbbfe8db4be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Ubah')])[2]</value>
      <webElementGuid>6975df74-8c85-4826-a682-9ffad434e7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin User'])[1]/following::a[1]</value>
      <webElementGuid>e982aee9-62f4-4838-b8a3-c596c2369b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMIN USER'])[1]/following::a[1]</value>
      <webElementGuid>6ebbe71c-96d2-4d4e-970e-90bccc251d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[1]/preceding::a[1]</value>
      <webElementGuid>dd88ed0f-8194-4b7f-8c80-0871dec044b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUPER USER'])[1]/preceding::a[2]</value>
      <webElementGuid>bf90d2cf-c08e-4983-8ed1-9ee8db990945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ubah']/parent::*</value>
      <webElementGuid>d5410491-a505-4a94-9d9e-328ac729983b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/emoney-admin/ind/user/approval/roleapprovallist:viewdetail/142?_csrf=bca5cf9a-b101-46b0-8113-a26978c29910')]</value>
      <webElementGuid>6e616c88-4edf-4adf-b592-5642070d0a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>f2212c21-4854-41c1-b3ce-a0a722b607e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/emoney-admin/ind/user/approval/roleapprovallist:viewdetail/142?_csrf=bca5cf9a-b101-46b0-8113-a26978c29910' and (text() = 'Ubah' or . = 'Ubah')]</value>
      <webElementGuid>16d77588-5e26-48f0-b3a7-5db5067d20c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
