<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Cheklist bisa Expired</name>
   <tag></tag>
   <elementGuidId>2b21572b-d0fa-4836-80f7-e3f0b50f4862</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='canExpiredLogin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#canExpiredLogin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>442b477b-489c-421a-9b38-1e9d4d518275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>canExpiredLogin</value>
      <webElementGuid>d285dd06-b745-4765-97fa-77f5528d1b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>canExpiredLogin</value>
      <webElementGuid>583b5caf-1f14-44c5-b175-28afad34772e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>30e61260-4b91-4fb2-8a56-c23e8d0dab11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;canExpiredLogin&quot;)</value>
      <webElementGuid>132c137b-fc71-47aa-b07d-e5a24fa6eb5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='canExpiredLogin']</value>
      <webElementGuid>8899566a-1cfc-4485-b060-fdfda54d7d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>62dd7173-a9f6-4248-bf52-4f2df963b392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>9d2f8691-c386-4bfe-b46c-81e1bdc20294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'canExpiredLogin' and @name = 'canExpiredLogin' and @type = 'checkbox']</value>
      <webElementGuid>7bbbced7-ab3c-4342-93b9-dbcc16c35dff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
