<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Cheklist Password Bisa Expired</name>
   <tag></tag>
   <elementGuidId>118360a0-336d-471c-8970-82617ed0aebe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='canExpiredPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#canExpiredPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8498b435-a71b-4397-90ad-b213831a2d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>canExpiredPassword</value>
      <webElementGuid>9a90a47c-9911-486f-93a8-988bf7505d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>canExpiredPassword</value>
      <webElementGuid>2c8f06e7-52bb-40c8-8b43-5a93235c4f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>238256e1-2656-4924-88f6-53c3897fba2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;canExpiredPassword&quot;)</value>
      <webElementGuid>ef988a97-f2c5-4712-a620-ffffcedfb990</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='canExpiredPassword']</value>
      <webElementGuid>97e27417-cb6e-4703-94f0-7635a2e8c768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>a20e0cce-1cc2-4ec2-a80b-734ae84e8deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>a65d4cd3-42f4-4927-a645-ce2f2eafc971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'canExpiredPassword' and @name = 'canExpiredPassword' and @type = 'checkbox']</value>
      <webElementGuid>3c7f8d51-45cc-4730-82f2-554c8126be92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
