<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Buutton Cheklist Inquery</name>
   <tag></tag>
   <elementGuidId>473bb6c8-78c7-4e07-89fa-bd3387d0e591</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cb3_']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cb3_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d55d1abf-5bba-40c3-bfb7-37c3f7fabebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>parentClick(this)</value>
      <webElementGuid>f63286d4-dfb6-4ca4-9a5d-b5571aaeb8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cb3_</value>
      <webElementGuid>ec2199c8-5455-4c03-bca9-5bf52f869f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cb3_</value>
      <webElementGuid>0e8093d2-9d97-42bc-9d6b-da6f09baf55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>36939002-4361-40ab-914c-06b7044d412c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cb3_&quot;)</value>
      <webElementGuid>21c65a3f-0734-4d60-9264-334e7eb07f8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cb3_']</value>
      <webElementGuid>07a33970-600d-496d-b82d-a3ab53cd40d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[5]/td[2]/b[2]/input</value>
      <webElementGuid>95b379a7-e6f0-490b-af0e-8010ab105ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b[2]/input</value>
      <webElementGuid>d32e12df-a6d1-4c5a-81a0-b8fbd8e73d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cb3_' and @name = 'cb3_' and @type = 'checkbox']</value>
      <webElementGuid>657b078b-2c52-4f00-92d6-2a6569b66f40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
