<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Data user Otorisasi Parameter</name>
   <tag></tag>
   <elementGuidId>7ff0927c-b51c-42af-9729-79294161030b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form']/div[2]/table/tbody/tr/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.dataType > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e759de59-de33-4a32-a246-81ceb6a9a7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/emoney-admin/ind/approval/pendingchangelist:viewdetail/3556/User?_csrf=bef5b23b-1e51-4467-8a08-04184b626059</value>
      <webElementGuid>d6191d16-901c-41d3-a429-aac537469ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User</value>
      <webElementGuid>6c151def-352a-4888-a28a-60dd2db2b5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;t-data-grid&quot;]/table[@class=&quot;t-data-grid&quot;]/tbody[1]/tr[@class=&quot;t-first&quot;]/td[@class=&quot;dataType&quot;]/a[1]</value>
      <webElementGuid>78cb0bbb-9fbf-40e4-a8c3-61838e19eadf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[2]/table/tbody/tr/td/a</value>
      <webElementGuid>57bfb94c-cb05-4d71-a4c3-394950617521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'User')])[11]</value>
      <webElementGuid>289808ed-1798-46c7-8a38-76513fb48b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal / Jam'])[1]/following::a[1]</value>
      <webElementGuid>5ce03e3f-5fa9-4d09-ab1f-44953926f109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aksi'])[1]/following::a[1]</value>
      <webElementGuid>bed159c6-3ebc-4141-965e-f6c804879506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QAPAC1'])[1]/preceding::a[1]</value>
      <webElementGuid>7a692c0c-0cdc-4ae2-8063-0200f05bc4e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah'])[1]/preceding::a[1]</value>
      <webElementGuid>65cdeab7-2f13-4c86-873b-c64a776a816f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User']/parent::*</value>
      <webElementGuid>ee72ad1d-4309-43f7-8170-ec4ab2a5bb5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/emoney-admin/ind/approval/pendingchangelist:viewdetail/3556/User?_csrf=bef5b23b-1e51-4467-8a08-04184b626059')]</value>
      <webElementGuid>78119cee-bba7-434d-b2da-2e9dd259c977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>d00903fd-77d7-4c80-b0e3-306804cb6dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/emoney-admin/ind/approval/pendingchangelist:viewdetail/3556/User?_csrf=bef5b23b-1e51-4467-8a08-04184b626059' and (text() = 'User' or . = 'User')]</value>
      <webElementGuid>60580c07-722f-4feb-9ef0-cfe2c129746a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
