<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page 17</name>
   <tag></tag>
   <elementGuidId>095fcdef-f31f-42da-a3ca-706a368b643b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form']/div[2]/div/a[12]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Go to page 17&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>050f77ce-67b7-446e-8790-3bb40d9d0897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Go to page 17</value>
      <webElementGuid>7acb580e-862c-4c6d-aa58-54d498325994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/emoney-admin/ind/approval/pendingchangelist.grid.pager/17?_csrf=d76bb1ff-1a47-4e67-b27d-0da02d2ffbcc</value>
      <webElementGuid>c48b46e5-8096-4f4d-9a3a-1b1b62955613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>9ba6d287-9afd-4486-b95f-78bec89fff91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;t-data-grid&quot;]/div[@class=&quot;t-data-grid-pager&quot;]/a[12]</value>
      <webElementGuid>ddc8f471-2008-4cb7-88a1-b6936bb19936</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[2]/div/a[12]</value>
      <webElementGuid>389c3630-dc33-4990-8f55-a4fe78b3e57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'17')]</value>
      <webElementGuid>13a06906-4c52-4222-9be2-6818e8a747e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otorisasi Parameter'])[2]/following::a[12]</value>
      <webElementGuid>40ecd07f-a55f-4f0a-988a-15f232f22917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data'])[1]/preceding::a[1]</value>
      <webElementGuid>7edbd160-1b76-42e2-acc5-6d45508d2887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan'])[1]/preceding::a[1]</value>
      <webElementGuid>63c60f35-ed04-4cc0-bc9c-fd53961a07d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='17']/parent::*</value>
      <webElementGuid>38e7b23a-8204-4ccd-9ca1-2f1ec6ee14a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/emoney-admin/ind/approval/pendingchangelist.grid.pager/17?_csrf=d76bb1ff-1a47-4e67-b27d-0da02d2ffbcc')]</value>
      <webElementGuid>d62a8d1c-8eb0-451a-ad8d-59bfae1a78b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[12]</value>
      <webElementGuid>98a10691-4551-4b11-bd9a-3f6bb13bedeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Go to page 17' and @href = '/emoney-admin/ind/approval/pendingchangelist.grid.pager/17?_csrf=d76bb1ff-1a47-4e67-b27d-0da02d2ffbcc' and (text() = '17' or . = '17')]</value>
      <webElementGuid>fa4c0f9c-00ea-476d-be8b-6eed3f3ef56b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
