<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown Platform</name>
   <tag></tag>
   <elementGuidId>e87826e4-679d-46c9-9f8a-8977a6dedc76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deviceType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='deviceType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>45b36f4c-ef5b-48c7-ac4b-4b68b738390d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deviceType</value>
      <webElementGuid>1cff9887-f61b-4eb6-9729-419f690c1f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deviceType</value>
      <webElementGuid>c6e00b76-57cf-447b-84cc-194d31e07843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AndroidiPhone</value>
      <webElementGuid>cb1193d4-433d-46b4-8cea-9b6188bfbdbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deviceType&quot;)</value>
      <webElementGuid>b30bbfad-c54f-437b-a2a7-9bee8d565e90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='deviceType']</value>
      <webElementGuid>2ab2797b-a2a8-49e2-bd7d-d00cbeb6adee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr/td[2]/select</value>
      <webElementGuid>c335698c-4ac2-458a-83a7-1b066d225a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platform'])[1]/following::select[1]</value>
      <webElementGuid>0ca343ad-5209-46de-9613-2189cf111c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Histori Aplikasi'])[1]/following::select[1]</value>
      <webElementGuid>79688116-9f06-4f43-99b1-7192aa7d1e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version ID (versi dalam angka)'])[1]/preceding::select[1]</value>
      <webElementGuid>85f497ee-6a38-4c4d-94cb-d7d8b13c142f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version (versi yg dilihat user)'])[1]/preceding::select[1]</value>
      <webElementGuid>c52197fb-0a58-4377-9ee0-ece82dfc489b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>135e5436-1543-4e71-bde0-8a3d71ed62ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'deviceType' and @name = 'deviceType' and (text() = 'AndroidiPhone' or . = 'AndroidiPhone')]</value>
      <webElementGuid>67b36083-f1ec-4a25-b340-6174f90ff5d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
