<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Version ID</name>
   <tag></tag>
   <elementGuidId>a7be6ecd-2e5f-4975-a5ee-f9d0bd703337</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#versionId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='versionId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c136a383-502d-4cf5-bb63-d68817b46b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>versionId</value>
      <webElementGuid>a356a354-b7ae-419b-b12c-e37cb2af332c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>versionId</value>
      <webElementGuid>6ccb42e6-aaa3-44c2-ba9d-085ac20589ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4dc02f13-ea3e-4186-bbf9-883199afcc5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;versionId&quot;)</value>
      <webElementGuid>dfd17353-561b-440d-9d9a-e44bea7326a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='versionId']</value>
      <webElementGuid>2826f9f9-006b-49a0-b979-7d6c8a36bc3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>592140cb-ed70-4eac-a2c4-40e1e6497b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>6676fc6a-35ed-4daf-881f-9c2810907015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'versionId' and @name = 'versionId' and @type = 'text']</value>
      <webElementGuid>16935886-38a3-4d32-a756-46a443acebdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
