<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Version</name>
   <tag></tag>
   <elementGuidId>01849d92-f420-4c51-ab4e-822351bfca4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#version</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='version']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0d2b004-2f86-41e5-a210-362edb146840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>version</value>
      <webElementGuid>c96c3143-d13d-4bfc-a014-6e095982dba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>version</value>
      <webElementGuid>2f9237d3-7b1e-4175-a4b9-3bcc34943ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d33839cc-f0fa-4d44-87b0-9704c0d480c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;version&quot;)</value>
      <webElementGuid>fe797ee0-7269-49a9-8947-6f8a8e5ea204</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='version']</value>
      <webElementGuid>596ece4f-3e4a-45ab-b851-44b8baa0d7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>69d8c806-db9b-417f-8d7a-d15c6203eef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>8ad6584d-11d0-4ce5-949b-904fba5a55c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'version' and @name = 'version' and @type = 'text']</value>
      <webElementGuid>cdabf4aa-5de4-4036-8d8b-dc866c9deace</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
