<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Perubahan</name>
   <tag></tag>
   <elementGuidId>67144fb2-d446-48de-a6aa-051f2d5f8a5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#changes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='changes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>14da3d0a-7bc0-4f77-9615-da7a8b0f4aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c16f9c71-0f09-4f04-b555-c9b5718bd571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>755bf50e-cae9-44df-968a-fb2a1b15694c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>changes</value>
      <webElementGuid>389a2674-dfcf-4d6b-936b-034710fc6423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>changes</value>
      <webElementGuid>2288d854-02cb-4db4-80d3-c4b04d820ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;changes&quot;)</value>
      <webElementGuid>5ef647fe-90cb-4128-8767-bb5621e4ac31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='changes']</value>
      <webElementGuid>fcdb9323-0d37-43de-b3cb-115e67eec773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[5]/td[2]/textarea</value>
      <webElementGuid>9257514a-d190-4986-9716-d1387851a3b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>00edde68-5803-4e51-80aa-c99801c197db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'changes' and @name = 'changes']</value>
      <webElementGuid>7449e682-b809-44c4-935a-2fd1b2bb2432</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
