<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Ubah QRIS CPM</name>
   <tag></tag>
   <elementGuidId>5d1979d1-5957-455d-964e-d787a7957b2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form']/div[2]/table/tbody/tr[4]/td[8]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.action > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cd36d014-c065-4df4-99ac-5077acfe0109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/emoney-admin-staging/ind/emoney/limitemoneyapprovallist:detail/2</value>
      <webElementGuid>6e5aeeff-c200-4646-94d3-6b9983312136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah</value>
      <webElementGuid>19aa284b-db9a-4136-9b27-b59db4ddbc01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;t-data-grid&quot;]/table[@class=&quot;t-data-grid&quot;]/tbody[1]/tr[@class=&quot;t-first&quot;]/td[@class=&quot;action&quot;]/a[1]</value>
      <webElementGuid>eeaa52b8-6e29-405e-b7f8-a75356217d07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[2]/table/tbody/tr/td[8]/a</value>
      <webElementGuid>843099bb-257f-4eb5-8083-cdbe6635ae85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Ubah')])[2]</value>
      <webElementGuid>4c7bbe3f-7f55-4193-8b32-3db1e0469295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tarik Tunai'])[1]/following::a[1]</value>
      <webElementGuid>003223d6-e02d-4f2e-b384-78ed7624b9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::a[1]</value>
      <webElementGuid>4b0959be-0af7-46dd-8cd7-a3a12926e88b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setor Tunai'])[1]/preceding::a[1]</value>
      <webElementGuid>f59a7146-246a-49cb-afa6-b1ebb839be47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah'])[2]/preceding::a[1]</value>
      <webElementGuid>e4c9cf22-4532-4c4b-ab77-43ecbd251c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ubah']/parent::*</value>
      <webElementGuid>8c0df731-62fe-43ec-a946-1c6462d7763c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/emoney-admin-staging/ind/emoney/limitemoneyapprovallist:detail/2')]</value>
      <webElementGuid>6c2e1e20-72e6-4222-afd5-87c0ca339324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a</value>
      <webElementGuid>a7792ef7-1cfe-4118-b658-3be65cd6eb9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/emoney-admin-staging/ind/emoney/limitemoneyapprovallist:detail/2' and (text() = 'Ubah' or . = 'Ubah')]</value>
      <webElementGuid>7a797d47-c871-4f86-8429-7a63df0b5470</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
