<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Max Frekuensi harian</name>
   <tag></tag>
   <elementGuidId>75b951d7-0ebd-4804-97b8-db7527267fe0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxFrequencyDaily']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#maxFrequencyDaily</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71daca05-3746-4aa5-ac2f-d4952ea64bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>64155764-31d1-45e4-ac44-16e818d33065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxFrequencyDaily</value>
      <webElementGuid>3718357d-b36b-4854-bd1b-76a4f55ed7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maxFrequencyDaily</value>
      <webElementGuid>99e33897-dd3a-4476-aa47-439db75a68a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a9004aff-e2a3-4544-8a52-079e9b1dc624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxFrequencyDaily&quot;)</value>
      <webElementGuid>7e646c1a-d170-45f7-aa80-b1c4f3913e82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxFrequencyDaily']</value>
      <webElementGuid>462f1e9d-9d18-4b68-bde3-77c2b7f49388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>e4ed75c8-3cf2-4fca-9e71-81f8613b9eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>a2203263-aaab-466b-82da-976e6b7a8476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'maxFrequencyDaily' and @name = 'maxFrequencyDaily' and @type = 'text']</value>
      <webElementGuid>3e2a4c39-8e05-4b6f-976e-c1c11a17cf3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
