<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Max Nominal</name>
   <tag></tag>
   <elementGuidId>43dae2aa-8ee6-47c2-897b-b5cdb63808b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxNominal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#maxNominal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d30fe2f6-193b-46e0-b5d9-59b49ee7c060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10000000</value>
      <webElementGuid>c8b8bac4-41e2-4c14-9533-68026e24630c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxNominal</value>
      <webElementGuid>2ef2d284-6c47-429a-8f9f-47e1e6884b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maxNominal</value>
      <webElementGuid>4c79d852-33f7-41f7-acf0-01880862e1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a6c6b95d-5d91-4b94-a598-64e99879ecb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxNominal&quot;)</value>
      <webElementGuid>a000d86d-1e61-4761-98c5-3b8522900f0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxNominal']</value>
      <webElementGuid>5dbe3e93-0a8e-47ca-84d7-c25392e6b654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>ebff108e-04f9-49c8-be77-f532306261c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>d9692127-8926-4b5c-af3a-4bd3d2a23e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'maxNominal' and @name = 'maxNominal' and @type = 'text']</value>
      <webElementGuid>2244cfb2-1328-4714-ad3a-752a1a02d116</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
