<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Max Frekuensi Bulanan</name>
   <tag></tag>
   <elementGuidId>d88a6f12-ae31-43df-b16a-755a9c8adcbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxFrequencyMonthly']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#maxFrequencyMonthly</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>145a91a8-63b8-4222-be8f-52008addbcfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>6aeda45e-3208-4972-8a96-3a20d62568f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxFrequencyMonthly</value>
      <webElementGuid>d7bf8b60-43d1-4684-9f8f-085b52d04f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maxFrequencyMonthly</value>
      <webElementGuid>5f76cdf4-591e-418b-aa65-3f46f63aa0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f1b4243-3caf-4815-9cd1-5709cb20d6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxFrequencyMonthly&quot;)</value>
      <webElementGuid>d028f706-c49b-4f4d-b9ec-55f2875ad34b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxFrequencyMonthly']</value>
      <webElementGuid>068f1964-323c-4078-a2e3-c6233310a8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>e77baa71-94ed-4de3-b3f7-932a83a00d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>6aaf5edb-cde9-492b-b456-2b0d31f06f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'maxFrequencyMonthly' and @name = 'maxFrequencyMonthly' and @type = 'text']</value>
      <webElementGuid>01c9e4da-52bc-46f2-9352-37993ac37506</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
