<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Max Harian</name>
   <tag></tag>
   <elementGuidId>25e789e8-78a2-4d65-bf47-033955b56e67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='maxDaily']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#maxDaily</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68b184dd-b010-49bc-bb1e-d03cf9aa995f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>20000000</value>
      <webElementGuid>9075d684-1217-4e9d-aff6-2b4f110318be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maxDaily</value>
      <webElementGuid>76b6252a-fa71-4180-9943-5c9f373fd8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maxDaily</value>
      <webElementGuid>b66de686-3d93-4c4d-8035-5d3bb651f5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8005ea78-1b8a-45e6-af6f-2f05e9980c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maxDaily&quot;)</value>
      <webElementGuid>d3e6f194-76ef-416c-af14-8b8d42e5bb8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='maxDaily']</value>
      <webElementGuid>3115f051-0980-4d98-a1bf-80ca5796187e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>84d4cda2-7f12-4046-a190-652c80b5e603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>e27678de-b8ad-42cf-bf75-ce4449528153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'maxDaily' and @name = 'maxDaily' and @type = 'text']</value>
      <webElementGuid>af3a974d-42dd-42e0-926f-f0e281768fec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
