<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Ubah</name>
   <tag></tag>
   <elementGuidId>b5964cd6-ebc9-4159-b91d-f1e84cfb2e38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form']/div[2]/table/tbody/tr[1]/td[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.action > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>032890c6-9bc4-4401-be02-828eef4fdb99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/emoney-admin/ind/product/approval/maintenancepaymentlistapprovalbank.edit/204?_csrf=2e47dd53-634c-4f19-bfd2-8ab65500593f</value>
      <webElementGuid>acf4f342-4c0e-492e-96df-da8a6f8756d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah</value>
      <webElementGuid>d5e7ca49-1795-4323-b84d-88a2b957e9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;t-data-grid&quot;]/table[@class=&quot;t-data-grid&quot;]/tbody[1]/tr[@class=&quot;t-first&quot;]/td[@class=&quot;action&quot;]/a[1]</value>
      <webElementGuid>9bb45144-18be-44e9-8e09-76415e9cd068</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[2]/table/tbody/tr/td[4]/a</value>
      <webElementGuid>41b13f4f-c1cc-48fd-9c22-1b7ab4c264d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Ubah')])[2]</value>
      <webElementGuid>b370d076-b6f1-4f8a-a12c-86ee3b64a920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDAM Kota Yogyakarta'])[1]/following::a[1]</value>
      <webElementGuid>81182b16-00f2-45ec-8b8d-865378712ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembayaran Air'])[1]/following::a[1]</value>
      <webElementGuid>77df363b-e1c8-40ad-911c-08c6d9bb23d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembayaran Air'])[2]/preceding::a[1]</value>
      <webElementGuid>b16fb86e-64fc-4b87-b8a1-0725075dc711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aetra'])[1]/preceding::a[1]</value>
      <webElementGuid>43fab25c-0bfe-4bbb-9373-c9b85affcdf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ubah']/parent::*</value>
      <webElementGuid>fdd8c130-645a-4432-b7ac-9c1763d0e527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/emoney-admin/ind/product/approval/maintenancepaymentlistapprovalbank.edit/204?_csrf=2e47dd53-634c-4f19-bfd2-8ab65500593f')]</value>
      <webElementGuid>99c39c0c-5ced-4d0f-86bf-cbe9edeecd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a</value>
      <webElementGuid>e6fd9a8b-1665-427c-8ff6-01fb0fd5d4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/emoney-admin/ind/product/approval/maintenancepaymentlistapprovalbank.edit/204?_csrf=2e47dd53-634c-4f19-bfd2-8ab65500593f' and (text() = 'Ubah' or . = 'Ubah')]</value>
      <webElementGuid>78da1b12-d9a2-4bfb-9a7d-eb980204b5a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
