<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Reset</name>
   <tag></tag>
   <elementGuidId>698cbca6-5e35-4841-bbc5-7752000c5009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reset_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reset_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f276a74c-ab24-4b8c-b323-5bc57797da72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grey_btn ml10</value>
      <webElementGuid>aa82322a-f0d7-4efe-86cf-c050c5b89c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Reset</value>
      <webElementGuid>9c3ce207-2a5b-4a33-9723-71e5d8e037b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reset_1</value>
      <webElementGuid>29054566-8854-4a3e-a605-e3aeaf7d9da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cancel</value>
      <webElementGuid>c0c46fa7-7f00-4f0a-98f6-9815062df3f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c12ede68-9d6c-458d-8a37-0f939c3b4a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reset_1&quot;)</value>
      <webElementGuid>ce50df1e-f2bb-4634-ba1a-ea96ad69c73d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reset_1']</value>
      <webElementGuid>f8430305-6754-4fa3-93b3-b52ae9f65cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/input</value>
      <webElementGuid>2cff842c-66bd-43c2-bf71-988ac93a56c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>1899907b-decb-4b8c-99cf-e6c1ef195922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reset_1' and @name = 'cancel' and @type = 'submit']</value>
      <webElementGuid>6942f483-0e98-43fc-ab56-a89997afa075</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
