<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Hapus</name>
   <tag></tag>
   <elementGuidId>0a9cc603-67a4-410d-918d-4b762d3a89f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form']/div[2]/table/tbody/tr[1]/td[6]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>40d69411-c8db-4343-88db-5bf01caceccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Anda yakin akan menghapus data?');</value>
      <webElementGuid>443ba1f0-04fc-469a-a05b-04b511bcc79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/emoney-admin-staging/ind/emoney/appversionemoneyapprovallist.delete/9</value>
      <webElementGuid>5aa933b0-6cc7-487f-a3a2-356efb27cb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hapus</value>
      <webElementGuid>13d350e3-cb25-4f23-a44f-d1d2ff93f5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;t-data-grid&quot;]/table[@class=&quot;t-data-grid&quot;]/tbody[1]/tr[@class=&quot;t-first&quot;]/td[@class=&quot;action&quot;]/a[2]</value>
      <webElementGuid>23f413ff-b38f-46df-bb1e-cf2f346bda46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;return confirm('Anda yakin akan menghapus data?');&quot;]</value>
      <webElementGuid>25a3c455-c8ce-4775-97dd-beeda3817338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[2]/table/tbody/tr/td[6]/a[2]</value>
      <webElementGuid>ba3c3d58-f18b-4c72-9197-4fcc4bb577dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hapus')]</value>
      <webElementGuid>ba77ff4e-1d02-46f9-accd-25c02b04b0a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah'])[1]/following::a[1]</value>
      <webElementGuid>19bb3841-7afb-49e4-9d4e-d1db379ec04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[1]/following::a[2]</value>
      <webElementGuid>b236021a-54e3-46e4-a059-4a1d826c36fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Android'])[3]/preceding::a[1]</value>
      <webElementGuid>8b924e47-7f32-4c04-8e62-71719b200470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya'])[2]/preceding::a[1]</value>
      <webElementGuid>4a9f6d9f-af9f-4837-a6ee-d55db03ff097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hapus']/parent::*</value>
      <webElementGuid>58d49aa4-431c-48bf-a21d-5fb6d6b8651f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/emoney-admin-staging/ind/emoney/appversionemoneyapprovallist.delete/9')]</value>
      <webElementGuid>29c8a464-5c29-4d40-bc6d-a2458b5dcada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>d1b77b31-6eea-4086-86ed-9f43636e27a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/emoney-admin-staging/ind/emoney/appversionemoneyapprovallist.delete/9' and (text() = 'Hapus' or . = 'Hapus')]</value>
      <webElementGuid>2ffe6b2a-5c4c-4d8f-b443-355b0eb9a6df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
