<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown Platform</name>
   <tag></tag>
   <elementGuidId>955b237c-2645-4bc4-8aa8-e0c3c287b1b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#platform</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='platform']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>36fa9490-fb6a-49e4-9fed-a77fe89aac7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>platform</value>
      <webElementGuid>4d59d477-e527-471a-9600-2a7ea767ec18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>platform</value>
      <webElementGuid>78501377-d1fa-41e9-8b07-2f0bc342eb89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[Tampilkan Semua]AndroidiPhone</value>
      <webElementGuid>b6379c35-9dd7-4b2e-9bd1-09f01ca0c78d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;platform&quot;)</value>
      <webElementGuid>1f36c30a-48e2-445d-aa9a-fecf66016702</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='platform']</value>
      <webElementGuid>515f7891-ea3c-44c3-aec2-ad7624892135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr/td[2]/select</value>
      <webElementGuid>59b9e525-86f9-4359-8adc-13aa7cb1fc4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platform'])[1]/following::select[1]</value>
      <webElementGuid>73468122-1bb8-4f16-a54c-183d8cb66e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Pencarian'])[1]/following::select[1]</value>
      <webElementGuid>ed7b4114-e506-4d6b-b2c4-484507f245d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platform'])[2]/preceding::select[1]</value>
      <webElementGuid>f5bf29b1-2aaf-454f-953e-28ae46dc168e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version ID'])[1]/preceding::select[1]</value>
      <webElementGuid>a5e00d64-6a42-431b-8b52-11f28c24c8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>0b70b9a3-1afb-43b0-936f-30c15cf8ff83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'platform' and @name = 'platform' and (text() = '[Tampilkan Semua]AndroidiPhone' or . = '[Tampilkan Semua]AndroidiPhone')]</value>
      <webElementGuid>d85467df-0a99-4df2-8dce-485beaa0736d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
