<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Customer PAN</name>
   <tag></tag>
   <elementGuidId>a82f8cad-e785-4fe2-aab9-4f034ad0f3fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customerPan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customerPan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>599ca2f8-a7e9-43a8-900d-79f6b7bd8c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-controls</value>
      <webElementGuid>571e5093-ec22-4769-8e16-1265b77125f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customerPan</value>
      <webElementGuid>be80a3c1-8c58-4305-a7c5-95c66a43f425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerPan</value>
      <webElementGuid>84dd0d15-d8b8-4cd7-a118-829b8856f53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7beab4b6-684a-48fa-8a90-3d957fc8e6bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customerPan&quot;)</value>
      <webElementGuid>a76a260d-199d-4a23-bd64-f532bc8bfa98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customerPan']</value>
      <webElementGuid>67844d89-77e0-434d-bb82-6e3b3a4b84c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>9a09eaec-c1e6-439b-8bbb-2bccc06ed046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>68f4d8bf-591d-4245-9cf4-3e44dad787b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'customerPan' and @name = 'customerPan' and @type = 'text']</value>
      <webElementGuid>9b809bb5-dd30-43af-9e03-3f9a1e44c3f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
