<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Periode Akhir</name>
   <tag></tag>
   <elementGuidId>108f97ca-4ac7-43b7-b31a-4ff76d432fa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='end']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#end</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a578b4aa-6cc3-49d6-8708-b9905c0a3139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>bc871f3b-fcae-46ba-993c-1f05e1870790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-controls</value>
      <webElementGuid>1e960f35-53ca-43f1-b696-2ce617353a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>14-01-2025</value>
      <webElementGuid>965b8c57-b8af-4cf0-9b3e-68be8e97133c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>end</value>
      <webElementGuid>9c676061-de57-4f18-ad1e-6eb6dd46674f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>end</value>
      <webElementGuid>9942f401-0312-474e-a8f8-bdf63b219ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a30af9cf-e002-4b3b-9e39-44271e2b5c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;end&quot;)</value>
      <webElementGuid>0638e2c2-b2c7-4076-a66a-47e1612ed648</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='end']</value>
      <webElementGuid>c493a0a7-51b3-4739-9728-f37afbdac067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[2]/td[2]/input[2]</value>
      <webElementGuid>890c0197-cbb2-46a4-b8e9-e8d2e030940b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input[2]</value>
      <webElementGuid>d5d9d6da-b92f-4a3d-abc4-3bb408b117d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'end' and @name = 'end' and @type = 'text']</value>
      <webElementGuid>bf7fb5bf-ad15-4397-9f37-7f3386e833cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
