<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Klik detail Nomor Rekening</name>
   <tag></tag>
   <elementGuidId>2147c67c-5b74-4328-99a5-f679d32591c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form']/div[2]/div/table/tbody/tr[1]/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.customerPhone > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>34283c82-d076-4c19-8fc5-3e2f56854768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/emoney-admin-staging/ind/emoney/customeremoneylist:viewdetail/51234</value>
      <webElementGuid>4fff663e-36bc-4a32-ade0-df25796642a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0895339895343</value>
      <webElementGuid>00d88695-fe7f-4511-ae9f-24bb45a4d9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[2]/div[@class=&quot;t-data-grid&quot;]/table[@class=&quot;t-data-grid&quot;]/tbody[1]/tr[@class=&quot;t-first&quot;]/td[@class=&quot;customerPhone&quot;]/a[1]</value>
      <webElementGuid>3ce1474c-e174-4823-866d-71765906766f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[2]/div/table/tbody/tr/td[2]/a</value>
      <webElementGuid>2fde6ab1-6c3d-43ba-ad10-5adb28f48992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'0895339895343')]</value>
      <webElementGuid>a5fd4a96-685b-48aa-aff4-470e8e495e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Astrid Alv'])[1]/following::a[1]</value>
      <webElementGuid>785cc96b-8231-4527-9a66-390dd3956329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Premium'])[2]/preceding::a[1]</value>
      <webElementGuid>43e361ce-82aa-42f9-98cf-205f7cbeff40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PACSTAGING'])[1]/preceding::a[1]</value>
      <webElementGuid>6a995b0c-f1a8-4e0b-abde-14f2889d3d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0895339895343']/parent::*</value>
      <webElementGuid>29cc3a5c-fa8f-4b89-8d93-fd404353b10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/emoney-admin-staging/ind/emoney/customeremoneylist:viewdetail/51234')]</value>
      <webElementGuid>d1e61d8d-6e83-424d-a5c5-c8b8019182f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>4a71234f-c291-428e-aaa6-be823b8d35d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/emoney-admin-staging/ind/emoney/customeremoneylist:viewdetail/51234' and (text() = '0895339895343' or . = '0895339895343')]</value>
      <webElementGuid>ee78aad8-f2da-44bc-bce6-b0d4f7cf7d83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
