<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Kembali</name>
   <tag></tag>
   <elementGuidId>3a47f2ea-d175-4da2-a363-5937a557c82d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='back']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#back</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9994d0e3-47b5-483d-9def-527166c5a7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grey_btn ml10</value>
      <webElementGuid>7bf4ea27-86c9-4253-804b-029b82ba5d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Kembali</value>
      <webElementGuid>b8e1ad03-a360-4b83-b02f-352ac50b65de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>back</value>
      <webElementGuid>b23cdd72-4dcb-4054-bdde-9e6d317d1e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cancel</value>
      <webElementGuid>6d6dab8c-1bf9-417b-b74b-35c9a17c7939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>194e6b4b-303d-48ea-a604-fab6160f4fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;back&quot;)</value>
      <webElementGuid>a0ae9bfa-1e84-43a5-8fb2-a2a57f6650a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='back']</value>
      <webElementGuid>47ee68c8-ff9c-499c-95ef-b4293e35165c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/input[2]</value>
      <webElementGuid>3eef67a4-da0e-424a-a524-1540d9e78178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input[2]</value>
      <webElementGuid>f38baef6-0ad4-4fd2-96fa-8ca4f6b45122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'back' and @name = 'cancel' and @type = 'submit']</value>
      <webElementGuid>9ee85b62-2846-4612-a385-af5094144403</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
