<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Ubah</name>
   <tag></tag>
   <elementGuidId>92bc7389-691b-4523-9bdd-3aee556fa15c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form']/div[2]/table/tbody/tr[1]/td[4]/a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.action > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d04e76c4-cb8c-4d8b-9ca6-78246b942d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/emoney-admin/ind/merchant/globalcategory:viewdetail/1?_csrf=62c9f0a5-1b9b-4675-9fa3-d2fc462fc46a</value>
      <webElementGuid>13b451fb-b2a3-4c18-b9e4-83eb2f7b438f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ubah</value>
      <webElementGuid>f3e637d7-e3ea-4e44-a7ab-aa1c3223d78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;t-data-grid&quot;]/table[@class=&quot;t-data-grid&quot;]/tbody[1]/tr[@class=&quot;t-first&quot;]/td[@class=&quot;action&quot;]/a[1]</value>
      <webElementGuid>703b13cc-4667-4eb8-b425-656be7e6d0b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[2]/table/tbody/tr/td[4]/a</value>
      <webElementGuid>362e2fae-5dd7-4f70-a061-a457330b83ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Ubah')])[2]</value>
      <webElementGuid>c3b1d768-3740-4389-afea-1a752ae1a75f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='P2G (P2G)'])[1]/following::a[1]</value>
      <webElementGuid>bccf005e-9d89-4e3a-a5fe-61722999dd8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khusus'])[1]/following::a[1]</value>
      <webElementGuid>2ae5a306-8f7e-432e-9ecd-eecc5af7b686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[1]/preceding::a[1]</value>
      <webElementGuid>e62b7ae8-96dd-4b49-966d-dd0063e09a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khusus'])[2]/preceding::a[2]</value>
      <webElementGuid>a57261f6-1142-4c43-bf03-2d40fd13e988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ubah']/parent::*</value>
      <webElementGuid>99c4fda3-5c24-4c1e-9aeb-344d06313c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/emoney-admin/ind/merchant/globalcategory:viewdetail/1?_csrf=62c9f0a5-1b9b-4675-9fa3-d2fc462fc46a')]</value>
      <webElementGuid>488edcad-7faa-4397-a104-9f4338cdf87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a</value>
      <webElementGuid>a91e6079-0184-4caf-9e56-3edbb7d3e655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/emoney-admin/ind/merchant/globalcategory:viewdetail/1?_csrf=62c9f0a5-1b9b-4675-9fa3-d2fc462fc46a' and (text() = 'Ubah' or . = 'Ubah')]</value>
      <webElementGuid>f3ab95c2-cb6e-4cb8-a13c-e48bb7afd404</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
