<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Nama Parameter</name>
   <tag></tag>
   <elementGuidId>287fb405-4cdd-4169-b53a-091361c5091c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#parameterName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='parameterName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13616de3-f88d-4a55-94c6-07184f11c180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>parameterName</value>
      <webElementGuid>04950bf2-608d-4844-b4b4-c8645851665f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parameterName</value>
      <webElementGuid>6cd3a2a3-15df-4a05-be7b-8b68e01239cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09afaa2d-cd7a-4cc9-a216-458d0daa8dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parameterName&quot;)</value>
      <webElementGuid>6f53de98-8c26-4c98-8b61-9d122d0d3774</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='parameterName']</value>
      <webElementGuid>ff906ba4-6e31-4e73-91b5-4dca3f945a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr/td[2]/input</value>
      <webElementGuid>5fc0b9a2-029e-42e4-a10e-1ae0372bd429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>980660c8-4dd2-48c9-a99c-2db58e127d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'parameterName' and @name = 'parameterName' and @type = 'text']</value>
      <webElementGuid>f2b7e727-4071-4708-a080-282e42fcb4a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
