<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Nilai Parameter</name>
   <tag></tag>
   <elementGuidId>552ff5a7-9677-48bb-a1af-301df0d3df87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#parameterValue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='parameterValue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d85c349-da78-48f3-858a-49215acfe52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>bdd46536-61e0-4d64-bfd8-e08c2514753c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0f83170c-3724-4dd8-97d6-3ac6f101a570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>parameterValue</value>
      <webElementGuid>7dccec7b-3cd7-4ad6-983b-b9b5c2fcf93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parameterValue</value>
      <webElementGuid>03a160a6-6892-4583-9499-906d4ad3e785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6b072b31-b7ba-4c2c-bdd5-4207fdc9078e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parameterValue&quot;)</value>
      <webElementGuid>3a66153d-850a-43da-9ffe-5884ae4187fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='parameterValue']</value>
      <webElementGuid>6a35edcf-a118-42e1-8fa7-d6ed957f5856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>a8723dcc-522b-40e7-8f95-6b92d7760d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>886b1961-6571-48b5-bfa1-91e9e639bd3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'parameterValue' and @name = 'parameterValue' and @type = 'text']</value>
      <webElementGuid>82dd52a1-8241-4f44-8ad6-1db0d9f2faf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
