<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button hapus</name>
   <tag></tag>
   <elementGuidId>afa7e503-85bb-4414-8a35-6838f78dbd34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form']/div[2]/table/tbody/tr[1]/td[6]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.action > a:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>186b912c-b041-4c00-ad94-aad90d6dcffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/emoney-admin/ind/user/approval/maintenanceuserapprovallist:confirmdelete/316?_csrf=596786ea-8dfb-464f-bda0-27a2f2831bb9</value>
      <webElementGuid>76e0f671-af81-4312-ad9b-4b3ac85fe900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hapus</value>
      <webElementGuid>399ebebb-31f8-4a94-882b-e59e78a38367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;t-data-grid&quot;]/table[@class=&quot;t-data-grid&quot;]/tbody[1]/tr[@class=&quot;t-first&quot;]/td[@class=&quot;action&quot;]/a[2]</value>
      <webElementGuid>4c99b97e-9a13-4f4a-be24-020a14707e07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[2]/table/tbody/tr/td[6]/a[2]</value>
      <webElementGuid>48f891f1-ffc7-45ff-b664-f9fe3d75d184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hapus')]</value>
      <webElementGuid>1377859b-7ecf-4d18-9917-f9a5b31b22cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah'])[1]/following::a[1]</value>
      <webElementGuid>fbc2763e-799b-4819-8e4a-9bfbdfcf09da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktif'])[2]/following::a[2]</value>
      <webElementGuid>86090209-e676-43cd-aee4-b6bf30f137a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AGNI'])[1]/preceding::a[1]</value>
      <webElementGuid>244e5c3c-8090-4484-b5b3-570dc101df87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='agni'])[1]/preceding::a[1]</value>
      <webElementGuid>6019ff88-c7d4-439b-8779-ff49e4f09a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hapus']/parent::*</value>
      <webElementGuid>05a3bb96-a898-4171-91b4-88e61c7e0f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/emoney-admin/ind/user/approval/maintenanceuserapprovallist:confirmdelete/316?_csrf=596786ea-8dfb-464f-bda0-27a2f2831bb9')]</value>
      <webElementGuid>fc5f11b4-6cb3-4a02-8cd2-a16399aa1f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a[2]</value>
      <webElementGuid>96eb82a1-0255-446d-87c1-2b045f6dc1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/emoney-admin/ind/user/approval/maintenanceuserapprovallist:confirmdelete/316?_csrf=596786ea-8dfb-464f-bda0-27a2f2831bb9' and (text() = 'Hapus' or . = 'Hapus')]</value>
      <webElementGuid>d84d2de0-d47b-4771-8791-d0684a7cb2ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
