<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown Unit Kerja Cabang</name>
   <tag></tag>
   <elementGuidId>49ec9ed6-6429-45bc-be5f-699ceb8a49f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='groupName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#groupName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>528ea88d-fe95-42f4-8425-c2e48c1af0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>groupName</value>
      <webElementGuid>ad1af927-5b02-4635-9cc9-efdfe8f49ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupName</value>
      <webElementGuid>2585705a-f1a5-4d3b-8bfd-3ad5749900ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[Tampilkan Semua]001 - Kantor Pusat002 - Kantor Cabang 21234 - &amp;ltimg src=x onerror=alert(1)&amp;gt</value>
      <webElementGuid>39cb435e-7782-4cbf-ae98-ab50577ee3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;groupName&quot;)</value>
      <webElementGuid>1a002176-2f6b-4dc1-9170-ecbe5ccbd4a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='groupName']</value>
      <webElementGuid>59191771-fb64-47be-96d5-231501f226df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[4]/td[2]/select</value>
      <webElementGuid>3e0c40d9-40df-40dd-9e1e-2fdcb3d592cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit Kerja / Cabang'])[2]/following::select[1]</value>
      <webElementGuid>7893f2fc-ca8e-4f69-b82c-b2b40f2746fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/following::select[2]</value>
      <webElementGuid>9fc91b22-fd10-4271-8f4d-023af9e54482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::select[1]</value>
      <webElementGuid>d43889b2-8480-40fa-9ad1-cb085245440a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[2]/preceding::select[2]</value>
      <webElementGuid>8608cbfe-d9b8-4a65-80b2-fade02154b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/select</value>
      <webElementGuid>a81ea257-5c97-4aca-985f-dfd7a9818e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'groupName' and @name = 'groupName' and (text() = '[Tampilkan Semua]001 - Kantor Pusat002 - Kantor Cabang 21234 - &amp;ltimg src=x onerror=alert(1)&amp;gt' or . = '[Tampilkan Semua]001 - Kantor Pusat002 - Kantor Cabang 21234 - &amp;ltimg src=x onerror=alert(1)&amp;gt')]</value>
      <webElementGuid>654c67b8-37d9-4749-8c96-c7e902bca2c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
