<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown Status</name>
   <tag></tag>
   <elementGuidId>81b113ed-3a96-4f4c-aee4-e11e6a50a387</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='status']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#status</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ce90d9d1-8691-4e78-831f-f1df6d47ce37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>2d8ab593-029f-4eab-870d-386ef170813c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>0dbb1f62-4884-4d90-a448-53236a6ab17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[Tampilkan Semua]AktifNon Aktif</value>
      <webElementGuid>c515841d-9d75-44a0-a96e-7aa007a471c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;status&quot;)</value>
      <webElementGuid>decb4a43-195f-43b7-8e09-0df034e8e231</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='status']</value>
      <webElementGuid>bd8e35e0-6740-4ab6-9dca-45646540df38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[5]/td[2]/select</value>
      <webElementGuid>acf70bf2-7cd5-4aee-a550-90392cce46ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[1]</value>
      <webElementGuid>5ae9e024-4db9-46d9-abfa-c846d13485ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit Kerja / Cabang'])[2]/following::select[2]</value>
      <webElementGuid>5f532244-2f59-4960-a255-3484141c758b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[2]/preceding::select[1]</value>
      <webElementGuid>e1080de4-9c34-4bdf-baf8-93a80609780e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[2]/preceding::select[1]</value>
      <webElementGuid>f4c7cc29-9e25-421a-9cf9-c4a584b4a0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/select</value>
      <webElementGuid>a93cca03-68d7-4e35-8368-ab507d96c4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'status' and @name = 'status' and (text() = '[Tampilkan Semua]AktifNon Aktif' or . = '[Tampilkan Semua]AktifNon Aktif')]</value>
      <webElementGuid>e0d2b1ac-44a5-4ff4-8146-889f7a2bf4a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
