<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown role</name>
   <tag></tag>
   <elementGuidId>4b105c6c-88d8-4cdf-ba2d-48adeebe3314</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='roleName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#roleName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d9f1ca6e-94ce-4621-a478-07361dbfea61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>roleName</value>
      <webElementGuid>6292b4e8-dace-4072-b2d4-bc0123243a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>roleName</value>
      <webElementGuid>564eed09-e5e3-4ba2-89a3-22d21a4c8899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[Tampilkan Semua]ADMIN USERSUPER USER</value>
      <webElementGuid>66b69b3c-8de4-4b8b-a040-df12cdb87100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;roleName&quot;)</value>
      <webElementGuid>a4a05b7f-ea49-4045-bf77-b438455739d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='roleName']</value>
      <webElementGuid>d738d023-cfb3-4133-b407-ada341fd39de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[3]/td[2]/select</value>
      <webElementGuid>569acdbf-9e07-4b48-b788-cbff2901bbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/following::select[1]</value>
      <webElementGuid>c83da8b8-642f-4ded-b87d-1910e9ba7d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[1]/following::select[1]</value>
      <webElementGuid>7ba1cacb-64bc-4a18-818b-7655527fb116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit Kerja / Cabang'])[2]/preceding::select[1]</value>
      <webElementGuid>fb955ec6-8578-4b0c-af4c-287773d84dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::select[2]</value>
      <webElementGuid>bf266966-85f6-474f-9f66-babcff76532e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>0ece4f30-25d3-4f41-95dc-d3f58130b155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'roleName' and @name = 'roleName' and (text() = '[Tampilkan Semua]ADMIN USERSUPER USER' or . = '[Tampilkan Semua]ADMIN USERSUPER USER')]</value>
      <webElementGuid>da63f6aa-4bc3-467d-bba2-344290c6c10b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
