<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Detail Rekening</name>
   <tag></tag>
   <elementGuidId>149d889b-e91b-4784-9deb-a563e8dd148d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form']/div[2]/table/tbody/tr[1]/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.customerPhone > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ad9c1f7d-89fd-4f74-a4ad-c895cd8b7747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/emoney-admin-staging/ind/emoney/resetsecurityquestionlist:resetquestion/51234</value>
      <webElementGuid>ec15e290-1863-4d5c-a9a0-fd9622b5b698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0895339895343</value>
      <webElementGuid>cbf32035-a592-4dbc-9c7e-3ada591e76f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;t-data-grid&quot;]/table[@class=&quot;t-data-grid&quot;]/tbody[1]/tr[@class=&quot;t-first&quot;]/td[@class=&quot;customerPhone&quot;]/a[1]</value>
      <webElementGuid>7d646d57-7b7c-4bd7-9cb2-da79417fdee0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[2]/table/tbody/tr/td[2]/a</value>
      <webElementGuid>bdff29a0-c434-490d-be9e-0405c134b528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'0895339895343')]</value>
      <webElementGuid>3cde87d8-338c-47ef-8f8e-182206ae31d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Astrid Alv'])[1]/following::a[1]</value>
      <webElementGuid>fab23006-4dd4-4b6d-8b47-c82d207e7c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Counter Salah Login'])[2]/following::a[1]</value>
      <webElementGuid>728741a9-dbf0-49a7-8bdd-939e2712275c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Premium'])[2]/preceding::a[1]</value>
      <webElementGuid>07162797-9c67-41da-bd66-28f59f863a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Astrid Alvianti'])[1]/preceding::a[1]</value>
      <webElementGuid>7a568f57-478a-420b-b7da-315057d2ce9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0895339895343']/parent::*</value>
      <webElementGuid>2de508b5-dda4-4ae4-9d55-8935467c17b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/emoney-admin-staging/ind/emoney/resetsecurityquestionlist:resetquestion/51234')]</value>
      <webElementGuid>a7fce5d1-1ad9-4c89-8a2b-e1309559bc28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>f0143e7d-dfbe-4d94-a4b1-8d9406ea4cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/emoney-admin-staging/ind/emoney/resetsecurityquestionlist:resetquestion/51234' and (text() = '0895339895343' or . = '0895339895343')]</value>
      <webElementGuid>26839961-6403-4036-a929-fdb95f5dc2be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
