<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Salah Security login</name>
   <tag></tag>
   <elementGuidId>8c0198e7-bfb3-4ea1-8d11-09b952f77eee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='failedQuestionAttempts']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#failedQuestionAttempts</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>103d755a-6016-4cb2-8056-4282158aafb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>9a1404bf-27d3-4e73-ac57-e5dbd1f076f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>a9fdf404-c199-4365-86d2-d481f5a9a727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>521276ab-3f59-4b7d-ad7c-4969d5ca8347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>failedQuestionAttempts</value>
      <webElementGuid>a7b2c472-fd8e-40dc-aa47-6fb637b09a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>failedQuestionAttempts</value>
      <webElementGuid>ca405252-c25d-4185-be63-10d04c98c854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e857841f-3271-4677-82f0-7ddf99011c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;failedQuestionAttempts&quot;)</value>
      <webElementGuid>c0c35060-3612-4b0b-ba76-7f822f7de77a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='failedQuestionAttempts']</value>
      <webElementGuid>2d10349d-40cd-420f-970e-df4bebcf7e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>88de8a85-278e-4144-8ff1-82fc72715279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>e834fc3f-b00c-484e-8141-a971ca9cf0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'failedQuestionAttempts' and @name = 'failedQuestionAttempts' and @type = 'text']</value>
      <webElementGuid>a33bf25c-c02a-4306-ba74-6cd04b38c916</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
