<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Code Referral</name>
   <tag></tag>
   <elementGuidId>4add8333-360d-45b8-b833-0d5d443120f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#referralCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='referralCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>291a2e32-1488-4226-a806-1505bc361d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>4c471e87-e890-4627-8aac-ee0a0adb4f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>referralCode</value>
      <webElementGuid>c81c50c7-39f2-4b88-8bf1-f0cf281ec5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>referralCode</value>
      <webElementGuid>27c565fe-efca-4b20-b1cc-ee407582ad36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e87f9142-c6ba-494f-988b-3b3793dd43ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;referralCode&quot;)</value>
      <webElementGuid>ef5d0289-3adf-409f-8604-3fc195b2fb94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='referralCode']</value>
      <webElementGuid>8e313daa-665a-42b5-a50b-f2b6974ee4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr/td[2]/input</value>
      <webElementGuid>0212b0d7-4610-4df8-a653-8428a07916d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>9b2e02cc-f26e-4f44-a770-a0ec676ec085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'referralCode' and @name = 'referralCode' and @type = 'text']</value>
      <webElementGuid>abb8b2d8-aea3-40d0-b9a4-4d697b64cd22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
