<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Referral Code</name>
   <tag></tag>
   <elementGuidId>562c94aa-c043-44f1-9cf6-f2adabb87756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#referralCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='referralCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>486d9662-83f1-4b5e-92b7-31fc3f7d726c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>referralCode</value>
      <webElementGuid>680121f8-9312-4498-9a1b-efd5cc6f05e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>referralCode</value>
      <webElementGuid>9d12a11a-fabc-4943-93d1-e4c3b93d53a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>439ef309-6d43-4635-bd93-f3bcaebcd4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;referralCode&quot;)</value>
      <webElementGuid>164a813a-bc73-4a34-86b5-2bd54fe50970</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='referralCode']</value>
      <webElementGuid>92afd126-d98d-453d-92d9-8130bb8e99e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr/td[2]/input</value>
      <webElementGuid>5649ec96-17ac-45dd-a231-e78a5d755fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>1b85a67d-f48c-4b22-a0ef-1b431e95a729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'referralCode' and @name = 'referralCode' and @type = 'text']</value>
      <webElementGuid>0b90ecbc-67ce-4853-a092-84fabc86c20e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
