<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Unit Kerja</name>
   <tag></tag>
   <elementGuidId>7bbd20bb-4363-44f0-bcd4-0a533aaf5995</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='groupName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#groupName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5d3f2e1-ad99-4025-b975-e29cba41602b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>groupName</value>
      <webElementGuid>4bf59e14-84ed-44dc-b6e4-c770a8226422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupName</value>
      <webElementGuid>dfe43e2b-4c8b-4305-9b56-0eb8a80bff0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9ca21bea-32ab-4e70-b418-75327afb062f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;groupName&quot;)</value>
      <webElementGuid>0160cbc4-825a-4792-bc2a-650d1ae9c2f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='groupName']</value>
      <webElementGuid>e7851339-693c-4111-a99c-13ecf173e0c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr/td[2]/input</value>
      <webElementGuid>cea45931-d2a8-4a2e-923c-d9aea864168f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>a940c463-99ae-4d85-9919-94903d97231f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'groupName' and @name = 'groupName' and @type = 'text']</value>
      <webElementGuid>8413b666-773f-4cf1-9140-34a1cfbb461f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
