<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Description QRIS</name>
   <tag></tag>
   <elementGuidId>b612d2d4-bd1d-4b4a-b79e-ad9136e6eb18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='descriptionQris']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#descriptionQris</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff9f712c-e1b6-4f48-a079-2e7f99bbe3d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>80d7e71a-b4d8-4d9c-b8b2-de1ef6896f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>descriptionQris</value>
      <webElementGuid>e8cc5b87-a97f-438c-acf9-76dbafe10833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>descriptionQris</value>
      <webElementGuid>bb8bacf2-50d4-4489-b67d-7cca798cca45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5aa39c50-84a4-4c85-87a1-4def1940fe9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;descriptionQris&quot;)</value>
      <webElementGuid>a8c55925-c259-4e76-a0d0-d71b648829f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='descriptionQris']</value>
      <webElementGuid>07558f1e-c97a-4051-9f50-d3eed81e0c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>a1641720-d648-4ada-9499-4b33490ed3d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>8643f319-c706-4137-8d58-9960a3b3d04a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'descriptionQris' and @name = 'descriptionQris' and @type = 'text']</value>
      <webElementGuid>941069bb-efc0-41ce-abf0-f79d4e4e9368</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
