<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checklist Password bisa Expired</name>
   <tag></tag>
   <elementGuidId>b5d5f9d3-c221-4c28-9d09-6182658723b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='canExpiredPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#canExpiredPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79c4df91-1a85-4894-98fd-6acad0b192b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>canExpiredPassword</value>
      <webElementGuid>64200704-9395-4b9b-bf93-c2517c49fe24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>canExpiredPassword</value>
      <webElementGuid>7013c4be-afc9-4004-a07c-f4a9b81167d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a7541656-bc0f-4d32-b551-49e3cbd3d1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;canExpiredPassword&quot;)</value>
      <webElementGuid>277e3916-14df-4feb-a336-1c22d3ff8382</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='canExpiredPassword']</value>
      <webElementGuid>85f3b419-49f8-4e83-ac6a-9b56208fa84f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>fa87bc85-0299-40e0-8577-5dee2f94760c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>c50b8334-d739-49af-be62-181bd011403f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'canExpiredPassword' and @name = 'canExpiredPassword' and @type = 'checkbox']</value>
      <webElementGuid>540b0b0a-5ea1-4b45-9b8d-c8bf9a2f4e69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
