<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checklist Login bisa Expired</name>
   <tag></tag>
   <elementGuidId>c2376750-b49a-42c3-8d73-770325b6f43d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='canExpiredLogin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#canExpiredLogin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85be5cd3-267f-4378-a48f-15c497264cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>canExpiredLogin</value>
      <webElementGuid>b8012040-6ffd-4183-8238-1b3aa19526b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>canExpiredLogin</value>
      <webElementGuid>4df6ed9a-3ff9-42c9-8403-08e10f950bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a04be752-d1b7-41e7-806e-4bbec52c40e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;canExpiredLogin&quot;)</value>
      <webElementGuid>c0401707-04fc-44aa-8e1b-1f208dac9521</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='canExpiredLogin']</value>
      <webElementGuid>57fe324a-8158-4973-a4b6-6798dec5a07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>eae8c63e-e074-4719-b8fc-5c816ccced20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>954e8e77-f9a2-47a5-a413-b9755318bade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'canExpiredLogin' and @name = 'canExpiredLogin' and @type = 'checkbox']</value>
      <webElementGuid>c853b164-28a8-4070-b6da-d8f3c1d9a6c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
