<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cheklist Administrasi User</name>
   <tag></tag>
   <elementGuidId>ee258f8c-d657-42ae-beb5-255ffe26c7f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cb1_']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cb1_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec39de93-9d11-44f2-ad92-45dd403219dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>parentClick(this)</value>
      <webElementGuid>ddb192df-2b99-4113-974b-64018f878a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cb1_</value>
      <webElementGuid>23dc5c46-8035-46c1-81a3-e9d8cac1c793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cb1_</value>
      <webElementGuid>62c3f864-b3e9-471a-ab81-525aaae51bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9ce724da-3c6e-4cc6-af3b-e8e95b12d437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cb1_&quot;)</value>
      <webElementGuid>ca068910-4a87-4cff-973f-059f4abc938f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cb1_']</value>
      <webElementGuid>740ed9e9-1efd-46d6-a834-a20df4ed33af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/fieldset/table/tbody/tr[5]/td[2]/b/input</value>
      <webElementGuid>0d66f85c-a3f2-4235-b3e8-e72d343c3c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b/input</value>
      <webElementGuid>fd416ce9-1721-4b7a-bc16-79f080fc8679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cb1_' and @name = 'cb1_' and @type = 'checkbox']</value>
      <webElementGuid>d997a725-65f8-404a-8e74-f16b13a3c264</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
